package pac

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/chiga0/agent-proxy/internal/config"
)

func Generate(cfg *config.Config) (string, error) {
	domains := cfg.EffectiveWhitelist()
	if len(domains) == 0 {
		return "", fmt.Errorf("whitelist is empty (no presets or custom domains enabled)")
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Auto-generated by agent-proxy - %s\n", time.Now().Format("2006-01-02 15:04:05"))
	fmt.Fprintf(&b, "// Effective whitelist: %d domains (presets: %v)\n", len(domains), cfg.Presets)
	b.WriteString("function FindProxyForURL(url, host) {\n")

	proxyHost := cfg.Proxy.EffectiveHost()
	for _, d := range domains {
		fmt.Fprintf(&b, "    if (dnsDomainIs(host, \".%s\") || host == \"%s\") return \"PROXY %s:%d\";\n",
			d, d, proxyHost, cfg.Proxy.Port)
	}

	b.WriteString("    return \"DIRECT\";\n")
	b.WriteString("}\n")

	return b.String(), nil
}

func Write(cfg *config.Config) error {
	content, err := Generate(cfg)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(config.DataDir(), 0700); err != nil {
		return err
	}
	return os.WriteFile(config.PACPath(), []byte(content), 0644)
}
