package pac

import (
	"fmt"
	"net"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/chiga0/agent-proxy/internal/config"
	"github.com/chiga0/agent-proxy/internal/rules"
)

func Generate(cfg *config.Config) (string, error) {
	domains := cfg.EffectiveWhitelist()
	// Merge cached remote rule domains (action: proxy)
	seen := make(map[string]bool, len(domains))
	for _, d := range domains {
		seen[d] = true
	}
	for _, d := range rules.CachedDomains(config.DataDir(), "proxy") {
		if !seen[d] {
			seen[d] = true
			domains = append(domains, d)
		}
	}
	if len(domains) == 0 {
		return "", fmt.Errorf("whitelist is empty (no presets or custom domains enabled)")
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Auto-generated by agent-proxy - %s\n", time.Now().Format("2006-01-02 15:04:05"))
	fmt.Fprintf(&b, "// Effective whitelist: %d domains (presets: %v)\n", len(domains), cfg.Presets)
	b.WriteString("function FindProxyForURL(url, host) {\n")

	proxyAddr := net.JoinHostPort(cfg.Proxy.EffectiveHost(), strconv.Itoa(cfg.Proxy.LocalPort()))
	for _, d := range domains {
		fmt.Fprintf(&b, "    if (dnsDomainIs(host, \".%s\") || host == \"%s\") return \"PROXY %s\";\n",
			d, d, proxyAddr)
	}

	b.WriteString("    return \"DIRECT\";\n")
	b.WriteString("}\n")

	return b.String(), nil
}

func Write(cfg *config.Config) error {
	content, err := Generate(cfg)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(config.DataDir(), 0700); err != nil {
		return err
	}
	return os.WriteFile(config.PACPath(), []byte(content), 0600)
}
