package pac

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/chiga0/agent-proxy/internal/config"
)

func Generate(cfg *config.Config) (string, error) {
	if len(cfg.Whitelist) == 0 {
		return "", fmt.Errorf("whitelist is empty")
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Auto-generated by agent-proxy - %s\n", time.Now().Format("2006-01-02 15:04:05"))
	fmt.Fprintf(&b, "// Whitelist: %d domains\n", len(cfg.Whitelist))
	b.WriteString("function FindProxyForURL(url, host) {\n")

	for _, d := range cfg.Whitelist {
		fmt.Fprintf(&b, "    if (dnsDomainIs(host, \".%s\") || host == \"%s\") return \"PROXY %s:%d\";\n",
			d, d, cfg.Proxy.Host, cfg.Proxy.Port)
	}

	b.WriteString("    return \"DIRECT\";\n")
	b.WriteString("}\n")

	return b.String(), nil
}

func Write(cfg *config.Config) error {
	content, err := Generate(cfg)
	if err != nil {
		return err
	}
	return os.WriteFile(config.PACPath(), []byte(content), 0644)
}
