package proxy

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/chiga0/agent-proxy/internal/config"
	"github.com/chiga0/agent-proxy/internal/pac"
	"github.com/chiga0/agent-proxy/internal/platform"
	"github.com/chiga0/agent-proxy/internal/tunnel"
)

func On(cfg *config.Config) error {
	var undo []func()

	fail := func(err error) error {
		for i := len(undo) - 1; i >= 0; i-- {
			undo[i]()
		}
		return err
	}

	// 1. Start SSH tunnel if enabled
	if cfg.Proxy.Tunnel {
		fmt.Print("  → SSH tunnel... ")
		if err := tunnel.Start(cfg); err != nil {
			fmt.Println("✗")
			return fmt.Errorf("start SSH tunnel: %w", err)
		}
		fmt.Println("✓")
		undo = append(undo, func() { tunnel.Stop(cfg) })
	}

	// 2. Generate PAC
	if err := pac.Write(cfg); err != nil {
		return fail(fmt.Errorf("generate PAC: %w", err))
	}

	// 3. Start PAC HTTP server (background daemon with PID file)
	fmt.Print("  → PAC server... ")
	if err := startPACDaemon(); err != nil {
		fmt.Println("✗")
		return fail(fmt.Errorf("start PAC server: %w", err))
	}
	fmt.Println("✓")
	undo = append(undo, stopPACDaemon)

	// 4. Set system PAC proxy
	service, err := platform.DetectNetworkService()
	if err != nil {
		return fail(fmt.Errorf("detect network: %w", err))
	}
	pacURL := fmt.Sprintf("http://127.0.0.1:%d/proxy.pac", config.PACPort)
	if err := platform.SetAutoProxy(service, pacURL); err != nil {
		return fail(fmt.Errorf("set PAC proxy: %w", err))
	}
	undo = append(undo, func() { platform.ClearAutoProxy(service) })

	// 5. Write CLI env file
	if err := writeEnvFile(cfg); err != nil {
		return fail(fmt.Errorf("write env file: %w", err))
	}
	undo = append(undo, func() { os.Remove(config.EnvPath()) })

	// 6. Install auto-start
	if err := platform.InstallAutoStart(cfg); err != nil {
		fmt.Printf("  ⚠ Auto-start: %v\n", err)
	} else {
		undo = append(undo, func() { platform.UninstallAutoStart() })
	}

	fmt.Printf("\n✓ Proxy enabled\n")
	fmt.Printf("  PAC (browser/desktop): %s\n", pacURL)
	fmt.Printf("  CLI env:               %s\n", config.EnvPath())
	fmt.Printf("  Proxy:                 %s:%d", cfg.Proxy.EffectiveHost(), cfg.Proxy.Port)
	if cfg.Proxy.Tunnel {
		fmt.Printf(" (via SSH tunnel → %s)", cfg.Proxy.Host)
	}
	fmt.Println()
	fmt.Printf("  Network service:       %s\n", service)
	fmt.Printf("  Whitelist:             %d domains (presets: %v)\n", len(cfg.EffectiveWhitelist()), cfg.Presets)
	fmt.Printf("\nCurrent terminal: source %s\n", config.EnvPath())
	return nil
}

func Off(cfg *config.Config) error {
	// 1. Disable system PAC proxy
	service, err := platform.DetectNetworkService()
	if err == nil {
		platform.ClearAutoProxy(service)
	}

	// 2. Stop PAC HTTP server daemon
	stopPACDaemon()

	// 3. Stop SSH tunnel
	if cfg.Proxy.Tunnel {
		tunnel.Stop(cfg)
	}

	// 4. Remove auto-start
	platform.UninstallAutoStart()

	// 5. Remove CLI env file
	os.Remove(config.EnvPath())

	fmt.Println("✓ Proxy disabled")
	fmt.Println("  Current terminal: unset https_proxy http_proxy no_proxy NO_PROXY")
	return nil
}

func pacPIDFile() string {
	return filepath.Join(config.DataDir(), "pac-server.pid")
}

func startPACDaemon() error {
	if pac.ServerRunning() {
		return nil
	}

	self, err := os.Executable()
	if err != nil {
		return err
	}

	cmd := exec.Command(self, "serve-pac")
	cmd.Stdout = nil
	cmd.Stderr = nil
	cmd.Stdin = nil
	if err := cmd.Start(); err != nil {
		return err
	}

	// Write PID file
	os.MkdirAll(config.DataDir(), 0700)
	os.WriteFile(pacPIDFile(), []byte(strconv.Itoa(cmd.Process.Pid)), 0644)

	go cmd.Wait()

	for i := 0; i < 20; i++ {
		time.Sleep(50 * time.Millisecond)
		if pac.ServerRunning() {
			return nil
		}
	}
	return fmt.Errorf("PAC server did not start within 1s")
}

func stopPACDaemon() {
	// Try PID file first
	if data, err := os.ReadFile(pacPIDFile()); err == nil {
		if pid, err := strconv.Atoi(strings.TrimSpace(string(data))); err == nil {
			if proc, err := os.FindProcess(pid); err == nil {
				proc.Kill()
			}
		}
		os.Remove(pacPIDFile())
		return
	}
	// Fallback: pgrep
	out, err := exec.Command("pgrep", "-f", "serve-pac").Output()
	if err != nil {
		return
	}
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		exec.Command("kill", line).Run()
	}
}

func writeEnvFile(cfg *config.Config) error {
	var b strings.Builder
	b.WriteString("# Auto-generated by agent-proxy\n")
	fmt.Fprintf(&b, "export https_proxy=%s\n", config.ShellQuote(cfg.ProxyURL()))
	fmt.Fprintf(&b, "export http_proxy=%s\n", config.ShellQuote(cfg.ProxyURL()))
	fmt.Fprintf(&b, "export no_proxy=%s\n", config.ShellQuote(cfg.NoProxyString()))
	b.WriteString("export NO_PROXY=\"${no_proxy}\"\n")

	return os.WriteFile(config.EnvPath(), []byte(b.String()), 0600)
}
