package proxy

import (
	"fmt"
	"os"
	"strings"

	"github.com/chiga0/agent-proxy/internal/config"
	"github.com/chiga0/agent-proxy/internal/pac"
	"github.com/chiga0/agent-proxy/internal/platform"
)

func On(cfg *config.Config) error {
	// 1. Generate PAC
	if err := pac.Write(cfg); err != nil {
		return fmt.Errorf("generate PAC: %w", err)
	}

	// 2. Start local PAC HTTP server
	if err := pac.StartServer(); err != nil {
		return fmt.Errorf("start PAC server: %w", err)
	}

	// 3. Set macOS system PAC proxy
	service, err := platform.DetectNetworkService()
	if err != nil {
		return fmt.Errorf("detect network: %w", err)
	}
	pacURL := fmt.Sprintf("http://127.0.0.1:%d/proxy.pac", config.PACPort)
	if err := platform.SetAutoProxy(service, pacURL); err != nil {
		return fmt.Errorf("set PAC proxy: %w", err)
	}

	// 4. Write CLI env file
	if err := writeEnvFile(cfg); err != nil {
		return fmt.Errorf("write env file: %w", err)
	}

	fmt.Printf("✓ Proxy enabled\n")
	fmt.Printf("  PAC (browser/desktop): %s\n", pacURL)
	fmt.Printf("  CLI env:               %s\n", config.EnvPath())
	fmt.Printf("  Proxy:                 %s:%d\n", cfg.Proxy.Host, cfg.Proxy.Port)
	fmt.Printf("  Network service:       %s\n", service)
	fmt.Printf("  Whitelist:             %d domains\n", len(cfg.Whitelist))
	fmt.Printf("\nCurrent terminal: source %s\n", config.EnvPath())
	return nil
}

func Off(cfg *config.Config) error {
	// 1. Disable macOS PAC proxy
	service, err := platform.DetectNetworkService()
	if err == nil {
		platform.ClearAutoProxy(service)
	}

	// 2. Stop local PAC HTTP server
	pac.StopServer()

	// 3. Remove CLI env file
	os.Remove(config.EnvPath())

	fmt.Println("✓ Proxy disabled")
	fmt.Println("  Current terminal: unset https_proxy http_proxy no_proxy NO_PROXY")
	return nil
}

func writeEnvFile(cfg *config.Config) error {
	var b strings.Builder
	b.WriteString("# Auto-generated by agent-proxy\n")
	fmt.Fprintf(&b, "export https_proxy=%s\n", cfg.ProxyURL())
	fmt.Fprintf(&b, "export http_proxy=%s\n", cfg.ProxyURL())
	fmt.Fprintf(&b, "export no_proxy=\"%s\"\n", cfg.NoProxyString())
	b.WriteString("export NO_PROXY=\"${no_proxy}\"\n")

	return os.WriteFile(config.EnvPath(), []byte(b.String()), 0644)
}
