# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentProxy < Formula
  desc "Domain-based selective proxy CLI for overseas ECS"
  homepage "https://github.com/chiga0/agent-proxy"
  version "0.7.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chiga0/agent-proxy/releases/download/v0.7.6/agent-proxy_0.7.6_darwin_amd64.tar.gz"
      sha256 "ff5065b56a5d0563a77ec7843f3a617aca12beeaad10fde64cbc850c425f8799"

      define_method(:install) do
        bin.install "agent-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chiga0/agent-proxy/releases/download/v0.7.6/agent-proxy_0.7.6_darwin_arm64.tar.gz"
      sha256 "a7881e4a5688bae46cc39d67c19354deba003334c4c199008f4866cb4d067a46"

      define_method(:install) do
        bin.install "agent-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chiga0/agent-proxy/releases/download/v0.7.6/agent-proxy_0.7.6_linux_amd64.tar.gz"
      sha256 "8951d6b04513eb0693b078fc3d71f501f803b2672bf30065d1b0aa7dd3ec025f"
      define_method(:install) do
        bin.install "agent-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chiga0/agent-proxy/releases/download/v0.7.6/agent-proxy_0.7.6_linux_arm64.tar.gz"
      sha256 "2df5568f1fdb1e3ba1fd265fe3b1e2eb496bb3349383111ce2c841256abf4b3b"
      define_method(:install) do
        bin.install "agent-proxy"
      end
    end
  end

  test do
    system "#{bin}/agent-proxy", "version"
  end
end
