# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentProxy < Formula
  desc "Domain-based selective proxy CLI for overseas ECS"
  homepage "https://github.com/chiga0/agent-proxy"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chiga0/agent-proxy/releases/download/v0.7.0/agent-proxy_0.7.0_darwin_amd64.tar.gz"
      sha256 "a5837a8f90a8be8585a1b0ec494d33ad9362f726ceb7ef8db25920c9eef9598b"

      define_method(:install) do
        bin.install "agent-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chiga0/agent-proxy/releases/download/v0.7.0/agent-proxy_0.7.0_darwin_arm64.tar.gz"
      sha256 "99c585381893982663d3751353bf3ed77ec029f530613116fad8d7f5f49b00cb"

      define_method(:install) do
        bin.install "agent-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chiga0/agent-proxy/releases/download/v0.7.0/agent-proxy_0.7.0_linux_amd64.tar.gz"
      sha256 "905c6538080b85ff9b8f94deae79a6d76da18e7ee350dfb85fb4d7f9f5f49ad7"
      define_method(:install) do
        bin.install "agent-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chiga0/agent-proxy/releases/download/v0.7.0/agent-proxy_0.7.0_linux_arm64.tar.gz"
      sha256 "bad4ef086cb340c2b6ffbd58824c1ab584311c5d435028d90f765c955b3bb6bb"
      define_method(:install) do
        bin.install "agent-proxy"
      end
    end
  end

  test do
    system "#{bin}/agent-proxy", "version"
  end
end
